# Generated by Django 5.0.3 on 2024-08-04 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=63, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
