# Generated by Django 5.0.3 on 2024-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_max_otp_try_user_otp_max_out_alter_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_otp_try',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_max_try',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
