# Generated by Django 5.0.3 on 2024-08-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequests',
            name='otp_done',
            field=models.BooleanField(default=False),
        ),
    ]
