# Generated by Django 5.0.3 on 2024-08-03 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_max_otp_try_user_otp_max_try_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_max_out',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_max_try',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images/'),
        ),
        migrations.CreateModel(
            name='VerificationRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=63, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('otp', models.SmallIntegerField(blank=True, null=True)),
                ('otp_max_try', models.SmallIntegerField(default=3)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('otp_max_out', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
