# Generated by Django 5.0.3 on 2024-08-03 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_otp_remove_user_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
