# Generated by Django 5.0.3 on 2024-08-05 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_verificationrequests_otp_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='available_working_hours',
        ),
        migrations.CreateModel(
            name='WorkAvailableHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nurse')),
            ],
            options={
                'unique_together': {('nurse', 'day')},
            },
        ),
    ]
