# Generated by Django 5.0.7 on 2024-08-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_city_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='admin_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
